[package]
name = "day3"
version = "0.1.0"
authors = ["Bo Williams <bo@livecat.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
